# Generated by Django 4.2.4 on 2023-08-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_rest_api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
