# Generated by Django 4.2.4 on 2023-08-20 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_rest_api', '0004_store_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='user_id',
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
