# Generated by Django 4.2.5 on 2023-09-04 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_rest_api', '0006_alter_store_user_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='+', to='store_rest_api.product'),
        ),
    ]
